### ISSUE TITLE
کتابخانه  image

### ISSUE THREAD

**Issue by shmf1385** [M0RT3Z4K/Hafez#1]
سلام

خسته نباشی

کتابخانه image رو باید از کجا نصب کنم؟

چون نه پیش فرض روی پایتون نصبه و نه با pip میشه نصبش کرد

**Comment by M0RT3Z4K** [comment]
اون یک فایل هست که کنار پروژه هست و نیاز به نصب نیست.
و اینکه پروژه فعلا خطا داره
باید دوباره آپلود بشه

**Comment by shmf1385** [comment]
سلام

ببخشید من ندیدمش😅😅
